### ISSUE TITLE
Botón Modo Oscuro/Modo Claro en Mi Carrito.

### ISSUE THREAD

**Issue by d-romero-dev** [Heltta/proyecto-jap-2023-g255-subg6#13]
En el documento  'cart.html'  no se visualiza el botón correspondiente para cambiar entre modo oscuro y modo claro. La funcionalidad existe pero el botón no es visible.

![image](https://github.com/Heltta/proyecto-jap-2023-g255-subg6/assets/141240040/657f06a5-f5fd-4eb2-8cef-e02d14e5abc6)

 ![image](https://github.com/Heltta/proyecto-jap-2023-g255-subg6/assets/141240040/ff901f2e-c6ee-4603-af4a-86545dfacda2)

**Comment by Heltta** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Botón Modo Oscuro/Modo Claro en Mi Carrito.](https://trello.com/c/qnaGSR5I/6-bot%C3%B3n-modo-oscuro-modo-claro-en-mi-carrito)
